[package]
name = "typst2anki"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["sgomezsal <sgomezsalazar7@gmail.com>"]
license = "MIT"
description = "Convert Typst files into Anki cards automatically."

homepage = "https://github.com/sgomezsal/typst2anki"
repository = "https://github.com/sgomezsal/typst2anki"
keywords = ["typst", "anki", "automation"]
categories = ["Education", "Tools"]
compiler = "0.12.0"
